const formatNames = {
  ARIA_DAY_LABEL: "ARIA_DAY_LABEL",
  ARIA_START_LABEL: "ARIA_START_LABEL",
  ARIA_END_LABEL: "ARIA_END_LABEL",
  ISO: "ISO",
  HEADER: "HEADER",
  DAY: "DAY",
  DAY_OF_WEEK_ABBREVIATED: "DAY_OF_WEEK_ABBREVIATED",
  DAY_OF_WEEK_FULL: "DAY_OF_WEEK_FULL",
  MONTH: "MONTH",
  MONTH_ABBREVIATED: "MONTH_ABBREVIATED",
  MONTH_FULL: "MONTH_FULL",
  YEAR: "YEAR"
};

export default formatNames;
